### ISSUE TITLE
Add TCK tests for MicroProfile LRA 1.0

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-lra#92]
I've got this idea from [MP concurrency](https://github.com/eclipse/microprofile-concurrency/issues/60). I would like to propose this issue as tracker for individual scenarios that should be included in the LRA TCK. Please when you create a PR for any scenario prefix this scenario with github pull request number and once it's merged please check its checkbox.

To add new scenario:

1. Propose scenario on this issue as comment or better directly in the agenda for the Monday hangout
2. The team will review new scenarios in Monday hangout 
3. If there are no objections it will be added to this list

Current scenarios:

- [x] #2 timelimit
- [x] #2 start LRA
- [x] #2 cancel LRA
- [x] #2 close LRA
- [x] #2 one level nested activity
- [x] #2 multi level nested activity complete
- [x] #2 multi level nested activity compensate
- [x] #2 multi level nested activity mixed complete and compensate outcomes
- [x] #2 join LRA via HTTP header
- [x] #2 join LRA when new one is started (REQUIRED, REQUIRES_NEW)
- [x] #2 leave LRA via annotation
- [x] #2 management of LRA in not annotated resource
- [x] #2 LRA recovery
- [x] #10 non LRA aware resource LRA propagation
- [X] #119 Multiple registrations by same participant within the same LRA should be ignored and related tests
- [x] #2 cancel on response code
- [x] #2 cancel on response code family
- [x] #99 cancel on family default -- 4xx really cancels LRA
- [x] #99 cancel on family default -- 5xx really cancels LRA
- [x] #99 cancel on family set to 3xx really cancels LRA
- [x] #99 cancel on family changed default is respected (i.e. change default to just 4xx and verify that 5xx code doesn't cancel LRA)
- [x] #99 cancel on set to precise status code really cancels LRA
- [x] #99 cancel on remote call -- call participant which starts the LRA and then makes a REST call to second `@LRA` annotated method which cancels the LRA through cancel on attributes
- [x] #122 add tests to validate that the LRA context is propagated correctly
- [ ] #117 Check that completed nested participants are told to forget when the top level LRA finishes
- [ ] #6 Include tests for time limits
- [ ] please add more scenarios here 

----
Deferred to 1.x (will open new issue after 1.0 release)
- [x] #2 leave LRA via client API
- [x] #2 get Active LRAs
- [x] #2 get all LRAs
- [x] #2 is particular LRA active
- [ ] `LRAClient#getCurrent` behavior when multiple LRAs are started
- [ ] LRA context propagation through CDI beans calls
- [ ] Client is subscribed by LRAManagement and then crashed and then recovered, the cancel/close should still be invoked on this participant

**Comment by xstefank** [comment]
This idea didn't really take off. I will close this issue and take note of the few proposed scenarios. If someone feels like it would be beneficial to still update it with the current state of the TCK, please let me know.
